<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */
?>
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */
<?php
          $owner = elgg_get_logged_in_user_entity();
			
			$online = OhYesChat::countOnline($owner);
			$total_notifications = OhYesChat::countNew();
			echo elgg_view('js/ohyes/');
            echo 'var OhYesChatData = ';
			echo json_encode(array(
							 'total' => array(
											  'notifications' => $total_notifications,
											  'online' => $online,
											  ),
							 ));
			echo ";";
?>
$('#ohyes-chat-count').html(OhYesChatData['total']['online']);
if(OhYesChatData['total']['notifications'] == 0){
  $('#chat-count-message').hide();
} if(OhYesChatData['total']['notifications'] !== 0){
   $('#chat-count-message').show().html(OhYesChatData['total']['notifications']);
}
