<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
*/ 
?>
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
var OhYesChat = OhYesChat ||{}; 
/**
 * Get online friends list
 * @param NULL;
 *
 * @return {Object}
 */
OhYesChat.FriendsShow = function(){
    $(".friends-list").show();
    $('#OhYesChat').attr('onclick', 'OhYesChat.FriendsHide();');
    $('.friends-list').find('.data').html('<div class="ohyes-chat-loading" style="padding:80px;"><div class="OhYesChat-Icon-Loading"></div></div>');       
   	$.ajax({
        url: '<?php echo elgg_get_site_url();?>ohyeschat/friends',
        type: 'get',
        success: function(data) { 
		    $('.friends-list').find('.data').html(data['friends']);
        } 
     });
};
/**
 * Remove open tab
 * @param div = id of div;
 *
 * @return {Object}
 */
OhYesChat.TabUnlink = function(div){
                $.ajax({
                          url: '<?php echo elgg_get_site_url();?>ohyeschat/action/removetab/'+div,
                          type: 'post',
                          success: function(fetch) { 
                                     if(fetch == 'removed'){
                                        $('#ohyeschat-window-'+div).remove();
                                      }
                             } 
                    });        
};
/**
 * Show a notification window
 * @param win = id of window;
 *
 * @return {Object}
 */
OhYesChat.NotifShow = function(win){
      $('.notification-window').show();
      $(win).attr('onclick', 'OhYesChat.NotifHide(this);');
      $('.ChatNotification').find('.data').html('<div class="ohyes-chat-loading"><div class="OhYesChat-Icon-Loading"></div></div>');       
             $.ajax({
                          url: '<?php echo elgg_get_site_url();?>ohyeschat/notif',
                          type: 'post',
                          success: function(fetch) { 
                                   $('.ChatNotification').find('.data').html(fetch['messages']);
                                   if(fetch['count'] !== '' ){
                                       $('#chat-count-message').show().html(fetch['count']);
                                   } 
                                   
                             } 
                    }); 

}
/**
 * Hide notification window
 * @param win = id of window;
 *
 * @return NULL;
 */
OhYesChat.NotifHide = function(win){
      $('.notification-window').hide();
      $(win).attr('onclick', 'OhYesChat.NotifShow(this);');

}
/**
 * Open a tab
 * @param id = id of tab;
 * @param div = id of div;
 *
 * @return {Object}
 */
OhYesChat.TabOpen = function(id, div){
            $('.ChatTab')
                     .not("#OhYesChat-Tab-"+id)
                     .css('width', '190px')
                     .find('.Tab-Title')
                     .hide();
            
            var tab = "#ohyeschat-window-"+id;
            $(".ChatTab").not("#ohyeschat-window-"+id).find('.box').hide(); 

            $(tab).css('width', '255px');
            $("#OhYesChat-Tab-"+id).show();
            $("#ohyeschat-window-"+id).find(".OhYesChat-Icon-Onine").hide();
            $("#ohyeschat-window-"+id).find('.box').show(); 
            close = 'OhYesChat.TabUnlink('+id+');';
            $("#OhYesChat-Tab-"+id).find('.options').attr('onclick', close);
            
            close = 'OhYesChat.TabClose('+id+', this);';
            $("#OhYesChat-Tab-"+id).find('.OhYesChat-Titles').attr('onclick', close);
            
            $('.ohyeschat-new-message').hide();
            $('.ohyeschat-new-message').find('.text').html('');
};
/**
 * Close a tab
 * @param id = id of tab;
 * @param div = id of div;
 *
 * @return {Object}
 */
OhYesChat.TabClose = function(id, div){
            var tab = "#ohyeschat-window-"+id;
            $(tab).css('width', '190px');
            $("#OhYesChat-Tab-"+id).hide();
            $("#ohyeschat-ustatus-"+id).show();
            $("#ohyeschat-window-"+id).find('.box').hide(); 
            
            open = 'OhYesChat.TabOpen('+id+',this);';
            $(div).attr('onclick', open);
};
/**
 * Hide friends list window
 *
 * @return NULL
 */
OhYesChat.FriendsHide = function(){
             $(".friends-list").hide();
             $('#OhYesChat').attr('onclick', 'OhYesChat.FriendsShow();');
};
/**
 * Open a new chat tab
 * @param div = id of div;
 *
 * @return {Object}
 */
OhYesChat.newTab = function(fid){
        if($(".OhYesChat").children(".ChatTab").size() >= 3){
               alert('Please close one tab to add new');
               return false;
        }
        if(fid){
                  	$.ajax({
                     url: '<?php echo elgg_get_site_url();?>ohyeschat/newtab/'+fid,
                     type: 'get',
                     success: function(data) { 
                             if($("#ohyeschat-window-" +fid).length == 0) { 
		                           if($(".OhYesChat").children(".ChatTab").size() < 4){
                                       $('.OhYesChat').append(data['tab']);
                                    } 
                                  if(data['messages']){
                                       $('#ohyes-chat-data-messages-'+fid).append(data['messages']); 
                                   }
                                   $("#ohyeschat-window-" +fid).find('.inner').click();
                               } 
                               else {
                                    $("#ohyeschat-window-" +fid).find('.inner').click();
                               }
                                     var chattab = document.getElementById('ohyes-chat-data-messages-'+fid);
                                     chattab.scrollTop = chattab.scrollHeight;
                             } 
                    });        
        } 
};
/**
 * Send a message
 * @param form = id of form;
 *
 * @return {Object}
 */
OhYesChat.Form = function(form){
$(function(){
           $('#ohyeschat-form-'+form).submit(function(e){
	          e.preventDefault(); 
                      data = $(this).serialize();
                       $.ajax({
                          url: '<?php echo elgg_get_site_url();?>ohyeschat/action/send',
                          type: 'post',
                          data: data,
                          success: function(fetch) { 
                                   $('#ohyeschat-window-'+form).find('.data').append(fetch['message']);
                                   $('#ohyeschat-form-'+form).find("#mbox").attr('value', '');
                                   	 var tab = form;
						             OhYesChat.RefeshMessages(tab);
					                 var chattab = document.getElementById('ohyes-chat-data-messages-'+tab);
                                     chattab.scrollTop = chattab.scrollHeight;
                             } 
                    });        
           }); 
       }); 
};
/**
 * Refesh messages in tab
 * @param form = id of form;
 *
 * @todo: why refresh entrie div? we should only append message if success
 * @return {Object}
 */

OhYesChat.RefeshMessages = function(form){
                       $.ajax({
                          url: '<?php echo elgg_get_site_url();?>ohyeschat/action/refresh?friend='+form,
                          type: 'post',
                          success: function(fetch) { 
                                   $('#ohyeschat-window-'+form).find('.data').html(fetch['message']);
                                   $('#ohyeschat-ustatus-'+form).attr('class', fetch['status']);
                                   if(fetch['count'] > 0){
                                     $('.ohyeschat-new-message').css('display', 'inline-block');
                                     $('.ohyeschat-new-message').find('.text').html(fetch['count']);
                                   }
                                 
                             } 
                    });        
};
/**
 * Boot OhYesChat
 *
 * @todo: lol i forgot todo for this;
 * @return {Object}
 */
OhYesChat.Boot = function(){
    $.ajax({
                          url: '<?php echo elgg_get_site_url();?>ohyeschat/bootsys/',
                          type: 'post',
                          success: function(fetch) {
                                   scripts = fetch;
                                   $('#ohyes-chat-js').html(scripts);
                                 
                             } 
                    });        
};
$(document).ready(function(){
         setInterval(function(){OhYesChat.Boot()}, 5000);      
}); 

/**
 * Play a sound on new message
 *
 * @todo: nil;
 * @return {mp3}
 */
OhYesChat.playSound = function(){ 
		document.getElementById('ohyes-chat-sound').play();
};

/**
 * Move scroll to end of tab
 *
 * @todo: nil;
 * @return null;
 */
OhYesChat.scrollMove = function(fid){ 
  var chattab = document.getElementById('ohyes-chat-data-messages-'+fid);
  chattab.scrollTop = chattab.scrollHeight;
};
/**
 * Register a url for icons
 *
 * @todo: nil;
 * @return  {Url}
 */
OhYesChat.emoticons = function(icon){
return "<img src='"+elgg.get_site_url()+"mod/OhYesChat/images/emoticons/ohyeschat-"+icon+".gif' />";
};
/**
 * Replace icons
 *
 * @params: message = message of user;
 * @return  {Url}
 */
OhYesChat.replaceEmoticons = function(messages){
   var message = messages.replace(':(', OhYesChat.emoticons('sad'))
                           .replace(':)', OhYesChat.emoticons('smile'))
                           .replace('=D', OhYesChat.emoticons('happy'))
                           .replace(";)", OhYesChat.emoticons('wink'));
   return message;                        
};