<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
foreach($vars['menu'] as $item){
	$url = $item['url'];
	$text = $item['text'];
	echo "<li><a href='{$url}'>{$text}</a></li>";	
}