<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
 ?>
<div class="module">
  <div class="head" id="module-green"><?php echo $vars['title'] ?> </div>
      <?php echo $vars['contents'] ?>
</div>
  