<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
$title = elgg_echo('track:user');
$params = array(
	'title' => $title,
	'content' =>  elgg_view('ohyes/chat/admin/trackuser'),
);

$body = elgg_view_layout(NULL, $params);

echo elgg_view_page($title, $body, 'ohyeschat');
