<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
 
$english = array(	
	'ohyes:chat:online' => 'Online',
	'ohyes:chat' => 'Chat',
	'ohyes:chat:total' => 'Chat (%s)',
	'ohyes:chat:notification' => 'Notifications',
	'ohyes:chat:no:online' => 'No friend is online',
	'ohyes:chat:no:message' => 'There is currently no message',


 );
					
add_translation("en", $english);
