<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */
if(elgg_is_logged_in()){
?>
<div id="ohyes-chat-js"  style="display:none;">
          <script type="text/javascript" src="<?php echo elgg_get_site_url();?>ohyeschat/boot/ohyeschat.boot.js"></script> 
</div>

<?php } ?>