<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
$v = new OhYesChat;
$version = $v->checkUpdate();
?>
  <div class="module-message" style="padding:20px;">
         <?php echo elgg_echo($version[0], array($version[1])); ?> 
   </div>
  