<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
 $latest  = OhYesChat::getLatest(4);
 $chat = new OhYesChat;
 foreach($latest as $message){
	  
	   $icon = elgg_view("icon/default", array(
														'entity' => get_user($message->sender), 
														'size' => 'small',
														));
	 ?>
  <div class="messages-item"  style="border-bottom: 1px solid #EEE;padding: 8px;">
      <div class="icon"  style="display:inline-table;">
        <?php echo $icon;?>
      </div>
      <div class="text" style="display:inline-table;position: absolute;padding: 10px;width:200px;">
      <?php echo OhYesChat::replaceIcon($chat->sttl($message->message, 20));?>
      </div>
  </div>
  
  <?php } ?>