<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
$action['is_action'] = true;
$action['text'] = 'Delete';
$action['href'] = 'action/ohyes/chat/deletemssages';
$url = elgg_view('output/url', $action);
?>
  <div class="module-message" style="padding:20px;">
         Total messages are <?php echo OhYesChat::getTotal();?>, delete messages older than one weak. This action is not reversable.
         <div class="button-yellow" style="margin-top:10px;"><?php echo $url;?></div>
  </div>
  