<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
?>
<div style="text-align:center;">
         <input type="text" placeholder="From" name="msgfrom"/>  
         <input type="text" placeholder="To" name="msgto"/> 
         <input type="submit" />
</div>