<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 

header('Content-Type: application/json'); 
$message = get_input('message');
$reciever = get_input('friend');
$sender = elgg_get_logged_in_user_entity()->guid;
$icon = elgg_view("icon/default", array(
														'entity' => get_user($sender), 
														'size' => 'small',
									));$SEND = new OhYesChat;
if($SEND->SendMessage($reciever, $message)){
   echo json_encode(array(
					 'message' => 	elgg_view('ohyes/chat/message-item', array(
																			   'icon' => $icon,
																			   'message' => $message
																			   ))
					 ));
} 
else {
  echo 'send:error';
}