<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */  
   
if(elgg_is_logged_in() && !OhYesChat::FromMobile()){
 echo elgg_view('ohyes/chat/bar_contents');
}