<?php
/**
 * OhYesChat
 * @website Link: https://informatikon.com
 * @package Informatikon.Elgg
 * @subpackage Chat
 * @author $arsalanshah.informatikon
 * @copyright All right reserved Informatikon Technologies 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */

$online_users = '<span id="ohyes-chat-count">'.OhYesChat::countOnline(elgg_get_logged_in_user_entity()).'</span>';
?>
<div class="OhYesChat">
    <div class="ChatNotification">
          <div class="inner" onClick="OhYesChat.NotifShow(this);">
              <div class="OhYesChat-Icon-Notification"></div>
              <div class="text" id="chat-count-message"></div>
          </div>
           <div class="notification-window" style="display:none;">
               <div class="OhYesChat-Titles">
                   <div class="OhYesChat-Inline-Table text"><?php echo elgg_echo('ohyes:chat:notification');?></div>
                   <div class="OhYesChat-Inline-Table options"> <div class="item"  onClick="OhYesChat.NotifHide(this, 1);"> X </div></div>
               </div>
            <div class="data">
			<?php   echo elgg_view('ohyes/chat/messages', array(
													   'entity' => elgg_get_logged_in_user_entity()
													   ));?>
                                        </div>   
          </div>
    </div>
    <div class="ChatBar">
         <div class="friends-list" style="display:none;">
               <div class="OhYesChat-Titles"  onClick="OhYesChat.FriendsHide();">
                   <div class="OhYesChat-Inline-Table text"><?php echo elgg_echo('ohyes:chat');?></div>
                   <div class="OhYesChat-Inline-Table options"> <div class="item"  onClick="OhYesChat.NotifHide(this, 1);"> X </div></div>          
               </div>
            <div class="data">
			<?php   echo elgg_view('ohyes/chat/friends', array(
													   'entity' => elgg_get_logged_in_user_entity(),
													   'json' => false
													   ));?>
                                        </div>   
          </div>
         <div class="inner" onClick="OhYesChat.FriendsShow();" id="OhYesChat">
            <div class="OhYesChat-Icon-UserOnine">
                        <div class="OhYesChat-Inner-Text"><?php echo elgg_echo('ohyes:chat:total', array($online_users));?></div>
            </div> 
          </div>
     </div>
     <?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
*/
	     if(is_array($_SESSION['ohyes_chat'])){
	     $tabs = array_unique($_SESSION['ohyes_chat']);
	     foreach($tabs as $tab){
		 $friend = get_user($tab);
		 echo elgg_view('ohyes/chat/selectfriend', array(
													   'friend' => $friend,
													   'xhr' => 'false'
													   ));
		 }
		 }
    ?>
       
</div>
