<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
*/ 
 $friend = $vars['entity'];
?>
 <div class="friends-list-item" onClick="OhYesChat.newTab(<?php echo $friend->guid;?>);"> 
                  <div class="icon"> <?php echo $vars['icon'];?></div>
                  <div class="name"><?php echo OhYesChat::sttl($friend->name, 20);?></div> 
                  <div class="OhYesChat-Icon-Onine"></div> 
 </div>