<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
*/ 
 $friend = $vars['entity'];
?>
 <div class="friends-list-item" style="margin: 5px 5px 5px 5px;" onClick="OhYesChat.newTab(<?php echo $friend->guid;?>);"> 
                  <div class="icon" style="display: inline-table;"> <?php echo $vars['icon'];?></div>
                  <div class="name" style="display: inline-table;margin-top: -10px;"><?php echo OhYesChat::sttl($friend->name, 20);?></div>  
                </div>