<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
*/ 
?>
<div class="message-item" style="margin-top: 10px;margin-bottom: 5px;min-height: 51px;border-bottom: 1px solid #EEE;">
                      <div class="">
                         <div class="OhYesChat-Inline" style="padding: 5px;"><?php echo $vars['icon'];?></div>
                         <div class="OhYesChat-Inline" id="ohyeschat-output-text" style="margin-top: -38px;margin-left: 50px;width: 177px;"><?php echo $vars['message'];?></div>
                      </div>
  </div>
 