<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
*/
if($vars['sender'] == elgg_get_logged_in_user_entity()->guid){
  $class = 'ohyeschat-message-text-sender';
  $triangle = 'ohyeschat-triangle-blue';
} 
else { 
  $class = 'ohyeschat-message-text';
  $triangle = 'ohyeschat-triangle-white';

}
if(empty($vars['icon'])){
     $containers = 'height:40px;width:40px;';	
}
?>
<style>

</style>
<div class="message-item" style="margin-top: 10px;margin-bottom: 5px;min-height: 51px;border-bottom: 1px solid #EEE;">
                      <div class="">
                         <div class="icon"><?php echo $vars['icon'];?></div>
                         <div class="ohyeschat-triangle <?php echo $triangle;?>"></div>
                         <div class="<?php echo $class;?>" id="ohyeschat-output-text" style="margin-top: -40px;"><?php echo $vars['message'];?></div>
                      </div>
  </div>
 