<?php
/**
 * OhYesChat
 * @website Link: https://github.com/lianglee/OhYesChat
 * @Package Ohyes
 * @subpackage Chat
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
$login_url = elgg_get_site_url();
echo '<div class="track-user-msg">';
echo elgg_echo('track:user:mesg');
echo '</div>';
echo elgg_view_form('ohyes/chat/trackuer', array('action' => "{$login_url}ohyeschat/admin/track"));